CREATE TABLE IF NOT EXISTS dashboard_preference (
  profile_id INT NOT NULL PRIMARY KEY,
  news_sources JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
