module.exports = {
	API_PORT: process.env.PORT || 3001,
	PUBLIC_SESSION_MESSAGE_DAILY_LIMIT:
		process.env.PUBLIC_SESSION_MESSAGE_DAILY_LIMIT || 100,
	PUBLIC_IP_MESSAGE_DAILY_LIMIT:
		process.env.PUBLIC_IP_MESSAGE_DAILY_LIMIT || 300,
};
