module.exports = {
	API_PORT: process.env.API_PORT || 8080,
	PUBLIC_SESSION_MESSAGE_DAILY_LIMIT:
		process.env.PUBLIC_SESSION_MESSAGE_DAILY_LIMIT || 100,
	PUBLIC_IP_MESSAGE_DAILY_LIMIT:
		process.env.PUBLIC_IP_MESSAGE_DAILY_LIMIT || 300,
	JWT_SECRET: process.env.JWT_SECRET || "",
	RECAPTCHA_SECRET: process.env.RECAPTCHA_SECRET || "",
	RECAPTCHA_PROJECT_ID: process.env.RECAPTCHA_PROJECT_ID || "",
	RECAPTCHA_SITE_KEY: process.env.RECAPTCHA_SITE_KEY || "",
};
